name: Hexo CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Configuration environment
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          mkdir ~/.ssh/
          echo "$SECRET" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git config --global user.email "roaldclark@gmail.com"
          git config --global user.name "Roald Clark"
      - name: Install dependencies
        run: npm install
      - name: Deploy Hexo
        run: |
          git clone https://github.com/roaldclark/hexo-theme-cards.git themes/cards
          npm run-script build
          npm run-script deploy
